import {
  School,
  AcademicYear,
  ClassModel,
  Student,
  StudentEnrollment,
  Course,
  CourseAssessment,
  AssessmentResult,
  AttendanceRecord,
  Profile,
  UserAccount,
} from "@/types";

export const INITIAL_PROFILE: Profile = {
  id: "user-admin-01",
  email: "admin@senbet.org",
  full_name: "መምህር ተክለ ማርያም (Tekle Maryam)",
  phone: "+251 91 100 2233",
  created_at: new Date().toISOString(),
};

export const INITIAL_USERS: UserAccount[] = [
  {
    id: "usr-admin-01",
    school_id: "sch-debre-mewi",
    email: "admin@senbet.org",
    full_name: "መምህር ተክለ ማርያም (Tekle Maryam)",
    role: "admin",
    is_owner: true,
    phone: "+251 91 100 2233",
    created_at: new Date().toISOString(),
  },
  {
    id: "usr-teacher-01",
    school_id: "sch-debre-mewi",
    email: "teacher@senbet.org",
    full_name: "መምህር ዳዊት ወልደሚካኤል (Dawit Woldemichael)",
    role: "teacher",
    is_owner: false,
    phone: "+251 91 222 3344",
    created_at: new Date().toISOString(),
  },
  {
    id: "usr-student-01",
    school_id: "sch-debre-mewi",
    email: "student@senbet.org",
    full_name: "ዮሐንስ ተስፋዬ (Yohannes Tesfaye)",
    role: "student",
    is_owner: false,
    phone: "+251 91 333 4455",
    created_at: new Date().toISOString(),
  },
  {
    id: "usr-staff-01",
    school_id: "sch-debre-mewi",
    email: "staff@senbet.org",
    full_name: "ወ/ሮ ማርታ ገብሬ (Marta Gebre)",
    role: "staff",
    is_owner: false,
    phone: "+251 91 444 5566",
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_SCHOOL: School = {
  id: "sch-debre-mewi",
  name: "ሰንበት ትምህርት ቤት",
  code: "SENBET-01",
  parish_name: "",
  phone: "+251 91 123 4567",
  email: "contact@senbet.org",
  address: "አዲስ አበባ, ኢትዮጵያ (Addis Ababa, Ethiopia)",
  created_at: new Date().toISOString(),
};

export const INITIAL_ACADEMIC_YEARS: AcademicYear[] = [
  {
    id: "ay-2017",
    school_id: "sch-debre-mewi",
    name: "2017 ዓ.ም",
    is_active: true,
    start_date: "2024-09-11",
    end_date: "2025-06-30",
    created_at: new Date().toISOString(),
  },
  {
    id: "ay-2016",
    school_id: "sch-debre-mewi",
    name: "2016 ዓ.ም",
    is_active: false,
    start_date: "2023-09-12",
    end_date: "2024-06-25",
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_CLASSES: ClassModel[] = [
  {
    id: "cls-g1",
    school_id: "sch-debre-mewi",
    academic_year_id: "ay-2017",
    name: "1ኛ ክፍል (Grade 1)",
    level_category: "ህጻናት (Children)",
    room_number: "ክፍል 101",
    created_at: new Date().toISOString(),
  },
  {
    id: "cls-g5",
    school_id: "sch-debre-mewi",
    academic_year_id: "ay-2017",
    name: "5ኛ ክፍል (Grade 5)",
    level_category: "መካከለኛ (Intermediate)",
    room_number: "ክፍል 204",
    created_at: new Date().toISOString(),
  },
  {
    id: "cls-g8",
    school_id: "sch-debre-mewi",
    academic_year_id: "ay-2017",
    name: "8ኛ ክፍል (Grade 8)",
    level_category: "ወጣቶች (Youth)",
    room_number: "አዳራሽ 2",
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: "stu-001",
    school_id: "sch-debre-mewi",
    student_id: "STU-2024-001",
    full_name: "ዮሐንስ ተስፋዬ (Yohannes Tesfaye)",
    baptismal_name: "ወልደ ጊዮርጊስ",
    gender: "male",
    date_of_birth: "2012-05-14",
    address: "አዲስ አበባ፣ ቀበሌ 04",
    parent_name: "ተስፋዬ ገብሬ",
    parent_phone: "+251 91 234 5678",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "stu-002",
    school_id: "sch-debre-mewi",
    student_id: "STU-2024-002",
    full_name: "ሰላማዊት አበራ (Selamawit Abera)",
    baptismal_name: "ወለተ ማርያም",
    gender: "female",
    date_of_birth: "2012-08-20",
    address: "አዲስ አበባ፣ ቀበሌ 06",
    parent_name: "አበራ ካሳ",
    parent_phone: "+251 92 345 6789",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "stu-003",
    school_id: "sch-debre-mewi",
    student_id: "STU-2024-003",
    full_name: "ዳዊት ግርማ (Dawit Girma)",
    baptismal_name: "ገብረ መስቀል",
    gender: "male",
    date_of_birth: "2012-01-10",
    address: "አዲስ አበባ፣ ቀበሌ 10",
    parent_name: "ግርማ ወርቁ",
    parent_phone: "+251 93 456 7890",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "stu-004",
    school_id: "sch-debre-mewi",
    student_id: "STU-2024-004",
    full_name: "ማርታ ኃይሌ (Marta Haile)",
    baptismal_name: "ወለተ ኪዳን",
    gender: "female",
    date_of_birth: "2012-11-03",
    address: "አዲስ አበባ፣ ቀበሌ 12",
    parent_name: "ኃይሌ በቀለ",
    parent_phone: "+251 94 567 8901",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "stu-005",
    school_id: "sch-debre-mewi",
    student_id: "STU-2024-005",
    full_name: "ኤፍሬም ደረጀ (Ephrem Dereje)",
    baptismal_name: "ኃይለ ሚካኤል",
    gender: "male",
    date_of_birth: "2012-03-25",
    address: "አዲስ አበባ፣ ቀበሌ 15",
    parent_name: "ደረጀ መላኩ",
    parent_phone: "+251 95 678 9012",
    status: "active",
    created_at: new Date().toISOString(),
  },
  {
    id: "stu-006",
    school_id: "sch-debre-mewi",
    student_id: "STU-2024-006",
    full_name: "በርናባስ አክሊሉ (Bernabas Aklilu)",
    baptismal_name: "ወልደ መድኅን",
    gender: "male",
    date_of_birth: "2016-04-12",
    address: "አዲስ አበባ፣ ቀበሌ 08",
    parent_name: "አክሊሉ ታደሰ",
    parent_phone: "+251 91 789 0123",
    status: "active",
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_ENROLLMENTS: StudentEnrollment[] = [
  {
    id: "enr-001",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-001",
    academic_year_id: "ay-2017",
    roll_number: 1,
    enrollment_status: "enrolled",
    created_at: new Date().toISOString(),
  },
  {
    id: "enr-002",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-002",
    academic_year_id: "ay-2017",
    roll_number: 2,
    enrollment_status: "enrolled",
    created_at: new Date().toISOString(),
  },
  {
    id: "enr-003",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-003",
    academic_year_id: "ay-2017",
    roll_number: 3,
    enrollment_status: "enrolled",
    created_at: new Date().toISOString(),
  },
  {
    id: "enr-004",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-004",
    academic_year_id: "ay-2017",
    roll_number: 4,
    enrollment_status: "enrolled",
    created_at: new Date().toISOString(),
  },
  {
    id: "enr-005",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-005",
    academic_year_id: "ay-2017",
    roll_number: 5,
    enrollment_status: "enrolled",
    created_at: new Date().toISOString(),
  },
  {
    id: "enr-006",
    school_id: "sch-debre-mewi",
    class_id: "cls-g1",
    student_id: "stu-006",
    academic_year_id: "ay-2017",
    roll_number: 1,
    enrollment_status: "enrolled",
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: "crs-bible-5",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    academic_year_id: "ay-2017",
    name: "መጽሐፍ ቅዱስ ጥናት (Bible Study)",
    code: "BIB-501",
    created_at: new Date().toISOString(),
  },
  {
    id: "crs-mezmur-5",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    academic_year_id: "ay-2017",
    name: "ዝማሬና ዜማ (Mezmur & Zema)",
    code: "MEZ-501",
    created_at: new Date().toISOString(),
  },
  {
    id: "crs-history-5",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    academic_year_id: "ay-2017",
    name: "የቤተክርስቲያን ታሪክ (Church History)",
    code: "HIS-501",
    created_at: new Date().toISOString(),
  },
  {
    id: "crs-faith-5",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    academic_year_id: "ay-2017",
    name: "ሥርዓተ ቤተክርስቲያንና ሃይማኖት (Faith & Dogma)",
    code: "FAI-501",
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_ASSESSMENTS: CourseAssessment[] = [
  {
    id: "asm-quiz-1",
    school_id: "sch-debre-mewi",
    course_id: "crs-bible-5",
    name: "የክፍል ፈተና (Quiz 1)",
    assessment_type: "quiz",
    max_score: 10,
    weight_percentage: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: "asm-midterm-1",
    school_id: "sch-debre-mewi",
    course_id: "crs-bible-5",
    name: "የግማሽ ዓመት ፈተና (Midterm Exam)",
    assessment_type: "midterm",
    max_score: 30,
    weight_percentage: 30,
    created_at: new Date().toISOString(),
  },
  {
    id: "asm-attendance-1",
    school_id: "sch-debre-mewi",
    course_id: "crs-bible-5",
    name: "ተሳትፎና ክትትል (Attendance & Participation)",
    assessment_type: "attendance",
    max_score: 10,
    weight_percentage: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: "asm-final-1",
    school_id: "sch-debre-mewi",
    course_id: "crs-bible-5",
    name: "የዓመት ማጠቃለያ ፈተና (Final Exam)",
    assessment_type: "final",
    max_score: 50,
    weight_percentage: 50,
    created_at: new Date().toISOString(),
  },
  // Assessments for Mezmur
  {
    id: "asm-mez-mid",
    school_id: "sch-debre-mewi",
    course_id: "crs-mezmur-5",
    name: "የዜማ ተግባር (Practical Chanting)",
    assessment_type: "midterm",
    max_score: 40,
    weight_percentage: 40,
    created_at: new Date().toISOString(),
  },
  {
    id: "asm-mez-fin",
    school_id: "sch-debre-mewi",
    course_id: "crs-mezmur-5",
    name: "የማጠቃለያ ፈተና (Final Exam)",
    assessment_type: "final",
    max_score: 60,
    weight_percentage: 60,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_RESULTS: AssessmentResult[] = [
  // Student 001 Bible Study
  {
    id: "res-001-q1",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-quiz-1",
    student_id: "stu-001",
    score: 9.5,
    remarks: "Excellent",
    created_at: new Date().toISOString(),
  },
  {
    id: "res-001-mid",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-midterm-1",
    student_id: "stu-001",
    score: 28.5,
    remarks: "Strong knowledge",
    created_at: new Date().toISOString(),
  },
  {
    id: "res-001-att",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-attendance-1",
    student_id: "stu-001",
    score: 10,
    remarks: "Always present",
    created_at: new Date().toISOString(),
  },
  {
    id: "res-001-fin",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-final-1",
    student_id: "stu-001",
    score: 47,
    remarks: "Top performer",
    created_at: new Date().toISOString(),
  },
  // Student 001 Mezmur
  {
    id: "res-001-mmid",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-mez-mid",
    student_id: "stu-001",
    score: 38,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-001-mfin",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-mez-fin",
    student_id: "stu-001",
    score: 57,
    created_at: new Date().toISOString(),
  },

  // Student 002 Bible Study
  {
    id: "res-002-q1",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-quiz-1",
    student_id: "stu-002",
    score: 8.5,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-002-mid",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-midterm-1",
    student_id: "stu-002",
    score: 26,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-002-att",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-attendance-1",
    student_id: "stu-002",
    score: 9,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-002-fin",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-final-1",
    student_id: "stu-002",
    score: 44,
    created_at: new Date().toISOString(),
  },
  // Student 002 Mezmur
  {
    id: "res-002-mmid",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-mez-mid",
    student_id: "stu-002",
    score: 36,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-002-mfin",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-mez-fin",
    student_id: "stu-002",
    score: 54,
    created_at: new Date().toISOString(),
  },

  // Student 003 Bible Study
  {
    id: "res-003-q1",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-quiz-1",
    student_id: "stu-003",
    score: 7,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-003-mid",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-midterm-1",
    student_id: "stu-003",
    score: 22,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-003-att",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-attendance-1",
    student_id: "stu-003",
    score: 8,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-003-fin",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-final-1",
    student_id: "stu-003",
    score: 38,
    created_at: new Date().toISOString(),
  },

  // Student 004 Bible Study
  {
    id: "res-004-q1",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-quiz-1",
    student_id: "stu-004",
    score: 9,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-004-mid",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-midterm-1",
    student_id: "stu-004",
    score: 27,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-004-att",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-attendance-1",
    student_id: "stu-004",
    score: 10,
    created_at: new Date().toISOString(),
  },
  {
    id: "res-004-fin",
    school_id: "sch-debre-mewi",
    assessment_id: "asm-final-1",
    student_id: "stu-004",
    score: 45,
    created_at: new Date().toISOString(),
  },
];

// Helper to generate today's date formatted as YYYY-MM-DD
export function getTodayDateString(): string {
  const d = new Date();
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

const todayStr = getTodayDateString();

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: "att-001",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-001",
    date: todayStr,
    status: "present",
    created_at: new Date().toISOString(),
  },
  {
    id: "att-002",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-002",
    date: todayStr,
    status: "present",
    created_at: new Date().toISOString(),
  },
  {
    id: "att-003",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-003",
    date: todayStr,
    status: "absent",
    remarks: "Sick leave",
    created_at: new Date().toISOString(),
  },
  {
    id: "att-004",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-004",
    date: todayStr,
    status: "present",
    created_at: new Date().toISOString(),
  },
  {
    id: "att-005",
    school_id: "sch-debre-mewi",
    class_id: "cls-g5",
    student_id: "stu-005",
    date: todayStr,
    status: "late",
    remarks: "Arrived at 9:15 AM",
    created_at: new Date().toISOString(),
  },
];
